apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsharedvpchosts.example.org
spec:
  group: example.org
  names:
    kind: XSharedVPCServiceProject
    plural: xsharedvpcserviceprojects
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                project:
                  type: string
                  description: GCP Project ID to enable for Shared VPC. Required.
                hostProject:
                  type: string
                  description: GCP Project ID of the Shared VPC Host Project. Required.
              required:
                - project
                - hostProject