apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xfolders.bhasha.org
spec:
  group: bhasha.org
  names:
    kind: XFolder
    plural: xfolders
  claimNames:
    kind: Folder
    plural: folders
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                displayName:
                  type: string
                  description: The folder display name. Required.
                parent:
                  type: string
                  description: The resource name of the parent Organization. Must be of the form organizations/{org_id}. Required.
                labels:
                  type: object
                  additionalProperties:
                    type: string
                parentRef:
                  type: object
                  description: Reference to a Folder in cloudplatform to populate parent.
                  properties:
                    name:
                      type: string
                      description: Name of the referenceable object.
                    policy:
                      type: object
                      description: Policies for referencing.
                      properties:
                        resolution:
                          default: Required
                          description: Resolution specifies whether resolution of this reference is required.
                          type: string
                          enum:
                            - Required
                            - Optional
                        resolve:
                          description: esolve specifies when this reference should be resolved.
                          default: Always
                          enum:
                            - Always
                            - IfNotPresent
                          type: string
                  required:
                  - name
              required:
                - displayName
                - parent