apiVersion: v1
kind: List
metadata:
  name: FolderList
items:
- apiVersion: bhasha.org/v1alpha1
  kind: Folder
  metadata:
    name: fldr-1
  spec:
    compositionRef:
      name: gcp-folder-composition
    displayName: fldr-1
    parentRef:
      name: lz-cross-plane-fldr
  
- apiVersion: bhasha.org/v1alpha1
  kind: Folder
  metadata:
    name: fldr-2
  spec:
    compositionRef:
      name: gcp-folder-composition
    displayName: fldr-2
    parentRef:
      name: lz-cross-plane-fldr
    
- apiVersion: bhasha.org/v1alpha1
  kind: Folder
  metadata:
    name: fldr-dev
  spec:
    compositionRef:
      name: gcp-folder-composition
    displayName: fldr-dev
    parentRef:
      name: fldr-1

- apiVersion: bhasha.org/v1alpha1
  kind: Folder
  metadata:
    name: fldr-prod
  spec:
    compositionRef:
      name: gcp-folder-composition
    displayName: fldr-prod
    parentRef:
      name: fldr-2