apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xfolders.bhasha.org
spec:
  group: bhasha.org
  names:
    kind: XFolder
    plural: xfolders
  claimNames:
    kind: Folder
    plural: folders
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                displayName:
                  type: string
                  description: The folder display name. Required.
                parent:
                  type: string
                  description: The resource name of the parent Organization. Must be of the form
                    folders/{folder_id} or organizations/{org_id}. Required.
                parentRef:
                  type: object
                  description: Reference to a Folder in cloudplatform to populate parent.
                  properties:
                    name:
                      type: string
                      description: Name of the referenceable object.
                    policy:
                      type: object
                      description: Policies for referencing.
                      properties:
                        resolution:
                          default: Required
                          description: Resolution specifies whether resolution of this reference is
                            required.
                          type: string
                          enum:
                            - Required
                            - Optional
                        resolve:
                          description: esolve specifies when this reference should be resolved.
                          enum:
                            - Always
                            - IfNotPresent
                          type: string
                  required:
                    - name
                parentSelector:
                  type: object
                  description: Selector for a Folder in cloudplatform to populate parent.
                  properties:
                    matchLabels:
                      type: object
                      description: MatchLabels ensures an object with matching labels is selected.
                      additionalProperties:
                        type: string
                    policy:
                      type: object
                      description: Policies for selection.
                      properties:
                        resolution:
                          type: string
                          default: Required
                          description: Resolution specifies whether resolution of this reference is
                            required. The default is 'Required', which means the
                            reconcile will fail if the reference cannot be
                            resolved. 'Optional' means this reference will be a
                            no-op if it cannot be resolved.
                          enum:
                            - Required
                            - Optional
                        resolve:
                          type: string
                          description: Resolve specifies when this reference should be resolved. The
                            default is 'IfNotPresent', which will attempt to
                            resolve the reference only when the corresponding
                            field is not present. Use 'Always' to resolve the
                            reference on every reconcile.
                          enum:
                            - Always
                            - IfNotPresent
              required:
                - displayName
