apiVersion: v1
kind: List
metadata:
  name: FolderList
items:
  - apiVersion: bhasha.org/v1alpha1
    kind: Folder
    metadata:
      name: fldr-1
      labels:
        role: fldr-1
    spec:
      compositionRef:
        name: gcp-folder-composition
      displayName: fldr-1
      parentSelector:
        matchLabels:
          role: lz-cross-plane-sahil
    
  - apiVersion: bhasha.org/v1alpha1
    kind: Folder
    metadata:
      name: fldr-2
      labels:
        role: fldr-2
    spec:
      compositionRef:
        name: gcp-folder-composition
      displayName: fldr-2
      parentSelector:
        matchLabels:
          role: lz-cross-plane-sahil
      
  - apiVersion: bhasha.org/v1alpha1
    kind: Folder
    metadata:
      name: fldr-dev
      labels: 
        role: fldr-dev
    spec:
      compositionRef:
        name: gcp-folder-composition
      displayName: fldr-dev
      parentSelector:
        matchLabels:
          role: fldr-1

  - apiVersion: bhasha.org/v1alpha1
    kind: Folder
    metadata:
      name: fldr-prod
      labels:
        role: fldr-prod
    spec:
      compositionRef:
        name: gcp-folder-composition
      displayName: fldr-prod
      parentSelector:
        matchLabels:
          role: fldr-2