apiVersion: v1
kind: List
metadata:
  name: projectlist
items:
- apiVersion: bhasha.org/v1alpha1
  kind: Folder
  metadata:
    name: fldr-bu1
  spec:
    compositionRef:
      name: gcp-folder-composition
    displayName: fldr-bu1
    parentRef:
      name: lz-cross-plane-fldr
  
- apiVersion: bhasha.org/v1alpha1
  kind: Folder
  metadata:
    name: fldr-bu2
  spec:
    compositionRef:
      name: gcp-folder-composition
    displayName: fldr-bu2
    parentRef:
      name: lz-cross-plane-fldr

- apiVersion: bhasha.org/v1alpha1
  kind: Folder
  metadata:
    name: fldr-bu3
  spec:
    compositionRef:
      name: gcp-folder-composition
    displayName: dev-lz
    parentRef:
      name: lz-cross-plane-fldr