apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-folder-composition
  labels:
    provider: provider-gcp
spec:
  compositeTypeRef:
    apiVersion: bhasha.org/v1alpha1
    kind: XFolder
  resources:
    - name: gcp-folder
      base:
        apiVersion: cloudplatform.gcp.upbound.io/v1beta1
        kind: Folder
        metadata:
          labels:
            crossplane.io/composite: ""
        spec:
          forProvider:
            displayName: ""
          providerConfigRef:
            name: default-gcp
      patches:
        - fromFieldPath: spec.displayName
          toFieldPath: spec.forProvider.displayName
        - fromFieldPath: spec.parentRef.name
          toFieldPath: spec.forProvider.parentRef.name
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.parent
          toFieldPath: spec.forProvider.parent
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.parentRef
          toFieldPath: spec.forProvider.parentRef
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.parentSelector
          toFieldPath: spec.forProvider.parentSelector
          policy:
            fromFieldPath: Optional
        - fromFieldPath: metadata.labels["crossplane.io/composite"]
          toFieldPath: metadata.labels["crossplane.io/composite"]