apiVersion: v1
kind: List
metadata:
  name: FolderList
items:
  - apiVersion: bhasha.org/v1alpha1
    kind: Folder
    metadata:
      name: fldr-1
      labels:
        role: fldr-1
    spec:
      compositionRef:
        name: gcp-folder-composition
      displayName: fldr-1
      parentRef:
        name: folders/178713639388
      # parentSelector:
      #   matchLabels:
      #     role: lz-cross-plane-sahil
      #     crossplane.io/claim-name: lz-cross-plane-sahil
    
  - apiVersion: bhasha.org/v1alpha1
    kind: Folder
    metadata:
      name: fldr-2
      labels:
        role: fldr-2
    spec:
      compositionRef:
        name: gcp-folder-composition
      displayName: fldr-2
      parentRef:
        name: folders/178713639388
      # parentSelector:
      #   matchLabels:
      #     role: lz-cross-plane-sahil
      
  - apiVersion: bhasha.org/v1alpha1
    kind: Folder
    metadata:
      name: fldr-dev
      labels: 
        role: fldr-dev
    spec:
      compositionRef:
        name: gcp-folder-composition
      displayName: fldr-dev
      parentRef:
        name: fldr-1

  - apiVersion: bhasha.org/v1alpha1
    kind: Folder
    metadata:
      name: fldr-prod
      labels:
        role: fldr-prod
    spec:
      compositionRef:
        name: gcp-folder-composition
      displayName: fldr-prod
      parentRef:
        name: fldr-2