apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xfolders.bhasha.org
spec:
  group: bhasha.org
  names:
    kind: XFolder
    plural: xfolders
  claimNames:
    kind: Folder
    plural: folders
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                displayName:
                  type: string
                  description: The folder display name. Required.
                parent:
                  type: string
                  description: The resource name of the parent Organization. Must be of the form organizations/{org_id}. Required.
              required:
                - displayName
                - parent