apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xscopedorgpolicies.bhasha.org
spec:
  group: bhasha.org
  names:
    kind: XScopedOrgPolicy
    plural: xscopedorgpolicies
  claimNames:
    kind: ScopedOrgPolicy
    plural: scopedorgpolicies
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                scopeType:
                  type: string
                  description: "The type of resource to apply the policy to. Must be one of: organization, folder, project."
                  enum:
                    - organization
                    - folder
                    - project
                scopeId:
                  type: string
                  description: "The ID of the resource to apply the policy to (e.g., organization ID, folder ID, project ID)."
                policyName:
                  type: string
                  description: "Name of the Policy to apply."
                enforce:  # <---- ADD THIS
                  type: string
                  description: "Enforce the policy: 'TRUE' or 'FALSE'."
              required:
                - scopeType
                - scopeId
                - policyName
                - enforce