apiVersion: example.org/v1alpha1
kind: OrgPolicy
metadata:
  name: my-disable-serial-port-policy
spec:
  compositionRef:
    name: gcp-org-policy-composition
  parent: organizations/1234567890123  # Replace with your organization ID
  spec:
    inheritFromParent: false #Example.  Customize as needed.
    reset: false #Example. Customize as needed.
    rules:
    - enforce: "FALSE"  #Example. Customize as needed.