apiVersion: bhasha.org/v1alpha1
kind: OrgPolicy
metadata:
  annotations:
    crossplane.io/external-name: iam.disableServiceAccountKeyUpload
  name: 
spec:
  compositionRef:
    name: gcp-org-policy-composition
  parent: projects/373728233549  # Replace with your organization ID
  spec:
    inheritFromParent: false
    reset: false
    rules:
    - enforce: "TRUE" # This will be used to override rule's enforce at org level.