apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-org-policy-composition
  labels:
    provider: provider-gcp-orgpolicy
spec:
  compositeTypeRef:
    apiVersion: bhasha.org/v1alpha1
    kind: XPolicy
  resources:
    - name: gcp-org-policy
      base:
        apiVersion: orgpolicy.gcp.upbound.io/v1beta1
        kind: Policy
        spec:
          forProvider:
            parent: "" # Replace with your actual organization ID. MUST BE SET!
            spec: 
              inheritFromParent: ""
              reset: ""
              rules:
              - enforce: ""
          providerConfigRef:
            name: default-gcp
      patches:
        - fromFieldPath: spec.parent
          toFieldPath: spec.forProvider.parent
        - fromFieldPath: spec.spec
          toFieldPath: spec.forProvider.spec

        
        