apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-org-policy-composition
  labels:
    provider: provider-gcp-orgpolicy
spec:
  compositeTypeRef:
    apiVersion: bhasha.org/v1alpha1
    kind: XOrgPolicy
  resources:
    - name: gcp-org-policy
      base:
        apiVersion: orgpolicy.gcp.upbound.io/v1beta1
        kind: Policy
        spec:
          forProvider:
            parent: organizations/1234567890123 # Replace with your actual organization ID. MUST BE SET!
            spec: {} #Leave the spec empty so that the patches apply
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parent
          toFieldPath: spec.forProvider.parent
        - type: FromCompositeFieldPath
          fromFieldPath: spec.spec
          toFieldPath: spec.forProvider.spec