apiVersion: bhasha.org/v1alpha1
kind: OrgPolicy
metadata:
  annotations:
    crossplane.io/external-name: iam.disableServiceAccountKeyUpload
    meta.upbound.io/example-id: orgpolicy/v1beta1/policy
    upjet.upbound.io/manual-intervention: Policy requires Org Access Rights
  name: primary
spec:
  compositionRef:
    name: gcp-org-policy-composition
  parent: projects/opensourcetools-poc  # Replace with your organization ID
  spec:
    inheritFromParent: false
    reset: false
    rules:
    - enforce: "TRUE" # This will be used to override rule's enforce at org level.