apiVersion: bhasha.org/v1alpha1
kind: ScopedOrgPolicy
metadata:
  name: my-project-policy-assignment
spec:
  compositionRef:
    name: gcp-scoped-org-policy-composition
  scopeType: project
  scopeId: gcp-project-id # Replace with your actual Project ID
  policyName: disable-serial-port-policy # Replace with the name of the existing Policy
  enforce: "TRUE"  # <---- ADD THIS