apiVersion: bhasha.org/v1alpha1
kind: Policy
metadata:
  name: primary
spec:
  compositionRef:
    name: gcp-org-policy-composition
  parent: projects/opensourcetools-poc  # Replace with your organization ID
  spec:
    inheritFromParent: false
    reset: false
    rules:
    - enforce: "TRUE"