apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpolicies.bhasha.org
spec:
  group: bhasha.org
  names:
    kind: XPolicy
    plural: xpolicies
  claimNames:
    kind: Policy
    plural: policies
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parent:
                  type: string
                  description: The parent of the resource.  Required.  Must be in the format organizations/{orgId}, folders/{folder_id}, projects/{project_id}.
                spec:
                  type: object
                  description: Basic information about the Organization Policy.
                  properties:
                    inheritFromParent:
                      type: boolean
                      description: Determines the inheritance behavior for this Policy.
                    reset:
                      type: boolean
                      description: Ignores policies set above this resource and restores the constraint_default enforcement behavior.
                    rules:
                      type: array
                      description: Up to 10 PolicyRules are allowed.
                      items:
                        type: object
                        properties:
                          allowAll:
                            type: string
                            description: Setting this to "TRUE" means that all values are allowed. This field can be set only in Policies for list constraints.
                          condition:
                            type: object
                            description: A condition which determines whether this rule is used in the evaluation of the policy.
                            properties:
                              description:
                                type: string
                                description: Optional. Description of the expression.
                              expression:
                                type: string
                                description: Textual representation of an expression in Common Expression Language syntax.
                              location:
                                type: string
                                description: Optional. String indicating the location of the expression for error reporting.
                              title:
                                type: string
                                description: Optional. Title for the expression.
                          denyAll:
                            type: string
                            description: Setting this to "TRUE" means that all values are denied. This field can be set only in Policies for list constraints.
                            pattern: "TRUE|FALSE"
                          enforce:
                            type: string
                            description: If "TRUE", then the Policy is enforced. If "FALSE", then any configuration is acceptable.
                            pattern: "TRUE|FALSE"
                          values:
                            type: object
                            description: List of values to be used for this PolicyRule. This field can be set only in Policies for list constraints.
                            properties:
                              allowedValues:
                                type: array
                                items:
                                  type: string
                                description: List of values allowed at this resource.
                              deniedValues:
                                type: array
                                items:
                                  type: string
                                description: List of values denied at this resource.
              required:
                - spec