apiVersion: bhasha.org/v1alpha1
kind: OrgPolicy
metadata:
  name: my-disable-serial-port-policy
spec:
  compositionRef:
    name: gcp-org-policy-composition
  parent: "organizations/373728233549"  # Replace with your organization ID
  spec:
    inheritFromParent: false #Example.  Customize as needed.
    reset: false #Example. Customize as needed.
    rules:
    - enforce: "TRUE"  #Example. Customize as needed.