apiVersion: bhasha.org/v1alpha1
kind: OrgPolicy
metadata:
  name: constraints/iam.disableServiceAccountKeyUpload
spec:
  compositionRef:
    name: gcp-org-policy-composition
  parent: projects/opensourcetools-poc  # Replace with your organization ID
  spec:
    inheritFromParent: false
    reset: false
    rules:
    - enforce: "TRUE" # This will be used to override rule's enforce at org level.