apiVersion: v1
kind: List
metadata:
  name: projectlist
items:
- apiVersion: bhasha.org/v1alpha1
  kind: Project
  metadata:
    name: lz-prod-01
  spec:
    compositionRef:
      name: gcp-project-composition
    name: project-a-id-02
    projectId: sahil-01-a-02
    billingAccount: "012478-27B604-6E78BE"
    folderIdSelector:
      matchLabels:
        role: fldr-prod
    autoCreateNetwork: false
    labels:
      app: prod-app
      owner: sahil
      cost-center: "1000"

- apiVersion: bhasha.org/v1alpha1
  kind: Project
  metadata:
    name: lz-dev-01
  spec:
    compositionRef:
      name: gcp-project-composition
    name: project-b-id-02
    projectId: sahil-02-b-02
    billingAccount: "012478-27B604-6E78BE"
    folderIdSelector:
      matchLabels:
        role: fldr-dev
    autoCreateNetwork: false
    labels:
      app: dev-app
      owner: sahil
      cost-center: "1010"