apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsharedvpcserviceprojects.bhasha.org
spec:
  group: bhasha.org
  names:
    kind: XSharedVPCServiceProject
    plural: xsharedvpcserviceprojects
  claimNames:
    kind: SharedVPCServiceProject
    plural: sharedvpcserviceprojects
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hostProject:
                  type: string
                  description: The ID of a host project to associate. Required.
                serviceProject:
                    description: The ID of the project that will serve as a SharedVPC service project. Required.
                    type: string
              required:
                - hostProject
                - serviceProject