apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnatgateways.example.org
spec:
  group: example.org
  names:
    kind: XNatGateway
    plural: xnatgateways
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the NAT Gateway. Required.
                region:
                  type: string
                  description: GCP region for the NAT Gateway. Required.
                routerRef:
                  type: string
                  description: Reference to the Router associated with the NAT Gateway. Required.
                sourceSubnetworkIPRangesToNat:
                  type: string
                  description: Source IP ranges for NAT. Options ALL_SUBNETWORKS_ALL_IP_RANGES, ALL_SUBNETWORKS_ALL_PRIMARY_IP_RANGES, LIST_OF_SUBNETWORKS.  Required.
              required:
                - name
                - region
                - routerRef
                - sourceSubnetworkIPRangesToNat