apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-project-composition
  labels:
    provider: provider-gcp
spec:
  compositeTypeRef:
    apiVersion: bhasha.org/v1alpha1
    kind: XProject
  resources:
    - name: gcp-project
      base:
        apiVersion: cloudplatform.gcp.upbound.io/v1beta1
        kind: Project
        spec:
          forProvider:
            name: my-crossplane-gcp-project  # Provide default value
            displayName: My Crossplane Managed GCP Project # Provide default value
            billingAccount: "012478-27B604-6E78BE"
            folderId: ""  # Replace with your actual folder ID
          providerConfigRef:
            name: default-gcp
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.name
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.displayName
          toFieldPath: spec.forProvider.displayName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.billingAccount
          toFieldPath: spec.forProvider.billingAccount
        - type: FromCompositeFieldPath
          fromFieldPath: spec.folderId
          toFieldPath: spec.forProvider.folderId