apiVersion: v1
kind: List
metadata:
  name: projectlist
items:
- apiVersion: bhasha.org/v1alpha1
  kind: Project
  metadata:
    name: project-one
    namespace: team-a
  spec:
    compositionRef:
      name: gcp-project-composition
    name: project-a-id
    displayName: "Team A's Project"
    billingAccount: "000000-000000-000000"

- apiVersion: bhasha.org/v1alpha1
  kind: Project
  metadata:
    name: project-two
  spec:
    compositionRef:
      name: gcp-project-composition
    name: project-b-id
    displayName: "Team B's Project"
    billingAccount: "000000-000000-000000"