apiVersion: v1
kind: List
metadata:
  name: ServiceAccountList
items:
- apiVersion: bhasha.org/v1alpha1
  kind: ServiceAccount
  metadata:
    name: sa-lz-list-02
  spec:
    compositionRef:
      name: gcp-sa-composition
    displayName: sa-cross-plane-poc-02
    project: sahil-01-00-002

- apiVersion: bhasha.org/v1alpha1
  kind: ServiceAccount
  metadata:
    name: sa-lz-list-03
  spec:
    compositionRef:
      name: gcp-sa-composition
    displayName: sa-cross-plane-poc-03
    project: sahil-01-00-002