apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: shared-vpc-host-project-composition
spec:
  compositeTypeRef:
    apiVersion: bhasha.org/v1alpha1
    kind: XSharedVPCHostProject
  resources:
    - name: shared-vpc-host-project
      base:
        apiVersion: compute.gcp.upbound.io/v1beta1
        kind: SharedVPCHostProject
        spec:
          forProvider:
            project: ""  # Provide default values for host project ID
          providerConfigRef:
            name: default-gcp
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.project
          toFieldPath: spec.forProvider.project