apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vpc-gcp
  labels:
    provider: provider-gcp
spec:
  compositeTypeRef:
    apiVersion: network.bhasha.org/v1alpha1
    kind: XVPC
  resources:
    - name: network
      base:
        apiVersion: compute.gcp.upbound.io/v1beta1
        kind: Network
        metadata:
          name: my-crossplane-vpc  # Set a default
        spec:
          forProvider:
            description: "" # Set a default
            autoCreateSubnetworks: false
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.name
          toFieldPath: metadata.name  # Corrected path!
        - type: FromCompositeFieldPath
          fromFieldPath: spec.description
          toFieldPath: spec.forProvider.description  # Corrected path!
        - type: FromCompositeFieldPath
          fromFieldPath: spec.autoCreateSubnetworks
          toFieldPath: spec.forProvider.autoCreateSubnetworks  # Corrected path!