apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vpc-gcp
  labels:
    provider: provider-gcp
spec:
  compositeTypeRef:
    apiVersion: network.bhasha.org/v1alpha1
    kind: XVPC
  resources:
    - name: network
      base:
        apiVersion: compute.gcp.upbound.io/v1beta1
        kind: Network
        metadata:
          name: my-crossplane-vpc
        spec:
          forProvider:
            description: "Default VPC description" # Set a default
            autoCreateSubnetworks: false # Provide default values for service project ID
          providerConfigRef:
            name: default-gcp
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.name
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.description
          toFieldPath: spec.spec.forProvider.description
        - type: FromCompositeFieldPath
          fromFieldPath: spec.autoCreateSubnetworks
          toFieldPath: spec.spec.forProvider.autoCreateSubnetworks