apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vpc-gcp
  labels:
    provider: provider-gcp
spec:
  compositeTypeRef:
    apiVersion: network.bhasha.org/v1alpha1
    kind: XVPC
  resources:
    - name: network
      base:
        apiVersion: compute.gcp.upbound.io/v1beta1
        kind: Network
        metadata:
          name: my-crossplane-vpc # Set a default for the network name. XR spec.name will override it.
        spec:
          forProvider:
            description: "VPC created by Crossplane" # Set a default.  XR spec.description will override it.
            autoCreateSubnetworks: false
          providerConfigRef:
            name: default-gcp  # Or your configured ProviderConfig name
      patches:
        - fromFieldPath: spec.name
          toFieldPath: metadata.name
        - fromFieldPath: spec.description
          toFieldPath: spec.spec.forProvider.description # Corrected path
        - fromFieldPath: spec.autoCreateSubnetworks
          toFieldPath: spec.spec.forProvider.autoCreateSubnetworks