apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvpcs.network.bhasha.org
spec:
  group: network.bhasha.org
  names:
    kind: XVPC
    plural: xvpcs
  claimNames:
    kind: VPC
    plural: vpcs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description:
                    type: string
                    default: "VPC created by Crossplane"
                autoCreateSubnetworks:
                  type: boolean
                  default: false
              required:
                - name