apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsubnets.bhasha.org
spec:
  group: bhasha.org
  names:
    kind: XSubnet
    plural: xsubnets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the Subnet. Required.
                ipCidrRange:
                  type: string
                  description: IP CIDR range for the Subnet. Required.
                region:
                  type: string
                  description: GCP region for the Subnet. Required.
                project:
                  description: |-
                    The ID of the project in which the resource belongs.
                    If it is not provided, the provider project is used.
                  type: string
                purpose:
                  description: |-
                    The purpose of the resource. This field can be either PRIVATE_RFC_1918, REGIONAL_MANAGED_PROXY, GLOBAL_MANAGED_PROXY, PRIVATE_SERVICE_CONNECT or PRIVATE_NAT(Beta).
                    A subnet with purpose set to REGIONAL_MANAGED_PROXY is a user-created subnetwork that is reserved for regional Envoy-based load balancers.
                    A subnetwork in a given region with purpose set to GLOBAL_MANAGED_PROXY is a proxy-only subnet and is shared between all the cross-regional Envoy-based load balancers.
                    A subnetwork with purpose set to PRIVATE_SERVICE_CONNECT reserves the subnet for hosting a Private Service Connect published service.
                    A subnetwork with purpose set to PRIVATE_NAT is used as source range for Private NAT gateways.
                    Note that REGIONAL_MANAGED_PROXY is the preferred setting for all regional Envoy load balancers.
                    If unspecified, the purpose defaults to PRIVATE_RFC_1918.
                  type: string
                role:
                    description: |-
                      The role of subnetwork.
                      Currently, this field is only used when purpose is REGIONAL_MANAGED_PROXY.
                      The value can be set to ACTIVE or BACKUP.
                      An ACTIVE subnetwork is one that is currently being used for Envoy-based load balancers in a region.
                      A BACKUP subnetwork is one that is ready to be promoted to ACTIVE or is currently draining.
                      Possible values are: ACTIVE, BACKUP.
                    type: string
                networkRef:
                  type: string
                  description: Reference to the Network to associate the subnet with
                privateIpGoogleAccess:
                  type: boolean
                  default: false
                  description: "Access Google API's via private subnet"
                secondaryIpRange:
                  type: array
                  items:
                    type: object
                    required:
                    - ipCidrRange
                    - rangeName
                    properties:
                      ipCidrRange:
                        type: string
                        description: IP CIDR range for the Subnet. Required.
                      rangeName:
                        type: string
                        description: Name of the Secondary Subnet. Required.
              required:
                - name
                - project
                - ipCidrRange
                - region
                - networkRef