apiVersion: v1
kind: List
metadata:
  name: NetworkList
items:
- apiVersion: bhasha.org/v1alpha1
  kind: Network
  metadata:
    name: my-vpc-01
  spec:
    compositionRef:
      name: vpc-gcp
    name: my-crossplane-vpc-01
    project: sahil-01-a-02
    description: "List 1 vpc created using XRD"
    autoCreateSubnetworks: false
    deleteDefaultRoutesOnCreate: true

- apiVersion: bhasha.org/v1alpha1
  kind: Network
  metadata:
    name: my-vpc-02
  spec:
    compositionRef:
      name: vpc-gcp
    name: my-crossplane-vpc-02
    project: sahil-01-a-02
    description: "List 2 vpc created using XRD"
    autoCreateSubnetworks: false
    deleteDefaultRoutesOnCreate: false