apiVersion: bhasha.org/v1alpha1
kind: Network
metadata:
  name: my-vpc
spec:
  compositionRef:
    name: vpc-gcp
  name: my-crossplane-vpc
  project: project-a-id-02
  description: "First VPC created using XRD"
  autoCreateSubnetworks: false
  deleteDefaultRoutesOnCreate: true