apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetwork.bhasha.org
spec:
  group: bhasha.org
  names:
    kind: XNetwork
    plural: xnetwork
  claimNames:
    kind: Network
    plural: networks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "Name of the VPC"  # Keeping description as property.
                project:
                  description: |-
                    The ID of the project in which the resource belongs.
                    If it is not provided, the provider project is used.
                  type: string
                description:
                  type: string
                  description: "A description of the VPC"
                autoCreateSubnetworks:
                  type: boolean
                  default: false
                deleteDefaultRoutesOnCreate:
                  description: |-
                      If set to true, default routes (0.0.0.0/0) will be deleted
                      immediately after network creation. Defaults to false.
                  type: boolean
                mtu:
                  description: |-
                    Maximum Transmission Unit in bytes. The default value is 1460 bytes.
                  type: number
                routingMode:
                  type: string
                  default: "GLOBAL"
                  enum: ["REGIONAL", "GLOBAL"]
              required:
                - name
                - project