apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vpc-gcp
  labels:
    provider: provider-gcp
spec:
  compositeTypeRef:
    apiVersion: bhasha.org/v1alpha1
    kind: XNetwork
  resources:
    - name: network
      base:
        apiVersion: compute.gcp.upbound.io/v1beta1
        kind: Network
        spec:
          forProvider:
            project: ""
            description: "Default VPC description"
            autoCreateSubnetworks: false
            deleteDefaultRoutesOnCreate: false
            routingMode: GLOBAL
            mtu: 1460
          providerConfigRef:
            name: default-gcp
      patches:
        - fromFieldPath: spec.name
          toFieldPath: metadata.name
        - fromFieldPath: spec.description
          toFieldPath: spec.forProvider.description
        - fromFieldPath: spec.autoCreateSubnetworks
          toFieldPath: spec.forProvider.autoCreateSubnetworks
        - fromFieldPath: spec.project
          toFieldPath: spec.forProvider.project
        - fromFieldPath: spec.deleteDefaultRoutesOnCreate
          toFieldPath: spec.forProvider.deleteDefaultRoutesOnCreate
        - fromFieldPath: spec.routingMode
          toFieldPath: spec.forProvider.routingMode
        - fromFieldPath: spec.mtu
          toFieldPath: spec.forProvider.mtu