apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-folder-composition
  labels:
    provider: provider-gcp
spec:
  compositeTypeRef:
    apiVersion: bhasha.org/v1alpha1
    kind: XFolder
  resources:
    - name: gcp-folder
      base:
        apiVersion: cloudplatform.gcp.upbound.io/v1beta1
        kind: Folder
        spec:
          forProvider:
            displayName: ""
            parent: ""
            parentRef:
              name: ""
              policy:
                resolution: Required
                resolve: Always
          providerConfigRef:
            name: default-gcp
      patches:
        - fromFieldPath: spec.displayName
          toFieldPath: spec.forProvider.displayName
        - fromFieldPath: spec.parent
          toFieldPath: spec.forProvider.parent